# This is the configuration used to check the rubocop source code.

require: rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - app/helpers/devise_helper.rb

Documentation:
  Enabled: false

LineLength:
  Max: 99

HasAndBelongsToMany:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/admin/**/*
Layout/EndOfLine: 
<<<<<<< HEAD
  EnforcedStyle: crlf
=======
  Enabled: false
>>>>>>> dd6f4114711d528480affeb496033f1cb0a760ec
