development: &development
  devise_jwt_secret_key: <%= ENV['DEVISE_JWT_SECRET_KEY'] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  redis_password: <%= ENV["REDIS_PASSWORD"] %>

test:
  <<: *development

production:
  <<: *development